### PR TITLE
opendata.py: seances: remap more missing/wrong idJO

### PR DESCRIPTION
**Pull request by paulineleon**

### CODE REVIEW

**Comment by RouxRC** [comment]
I'm not really in favor of this change for two reasons:
- As the maintainer who needs quite often to quickfix, it's way faster and simplier for me to just maintain a map of scrutin number => seance id (that i can see on the web, not the internal data one)
- Also I feel like the change [here](https://github.com/regardscitoyens/nosdeputes.fr/pull/130/files#diff-37e7bcb21947cdb277be465918445bd0L306-R325) can cause more changes than the intended ones. I tried to run parse_scrutin locally with this branch while having the prod data and it resulted in a lot of parsed scrutins being updated whereas my understanding is this cleanup should not impact any resulting parsed data

**Comment by paulineleon** [comment]
I understand the rationale for the intermediate map, thanks for explaining. Although it is a duplicate, it serves a useful purpose. Would you like me to amend the patch so as to keep it? It would be empty since the other map addresses all current problems (as identified by [this script](https://git.en-root.org/tricoteuses/tricoteuses-assemblee/-/blob/master/src/bugs/agenda-00002.ts)). But you could add to it as you're used to the next time you face the same kind of problem.

Since I don't have the production data I can't try to explain why there are more changes than expected. Do you find that some of these changes are incorrect?

> this cleanup should not impact any resulting parsed data

I can't comment on this because I don't (yet) fully understand the logic.

**Comment by RouxRC** [comment]
Yeah that would be an acceptable solution I guess to keep the intermediate map code, even empty.

Sorry I didn't take enough time to try and investigate what all the differences are yet, I can try and do that next week-end, I just noticed the script said scrutin updated for many ones whereas I guess it shouldn't.
I can put online a zip with the prod's content of the loaded and scrutins directories also if you wanna try yourself

**Comment by paulineleon** [comment]
> I can put online a zip with the prod's content of the loaded and scrutins directories also if you wanna try yourself

I'd be happy to investigate. I may get lost but will learn a bit more about the codebase in the process :grin:

**Comment by RouxRC** [comment]
stop by our IRC and i'll give you a link :)

**Comment by paulineleon** [comment]
Running **parse_scrutins.py 15** using a fresh checkout of the proposed branch and comparing it with a run from master (or from the file you sent me since they are identical), I get the following differences:

<pre>
for j in scrutin_*.json ; do if ! cmp -s $j /tmp/scrutins/$j ; then echo $j ; node_modules/.bin/jsondiffpatch $j /tmp/scrutins/$j ; fi ; done
scrutin_15_01692.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01693.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01694.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01695.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01696.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01697.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01698.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01699.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01700.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01701.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01702.json
{
  seance: "20190153" => "20190152"
}
scrutin_15_01703.json
{
  seance: "20190153" => "20190152"
}
</pre>

Which are explained because the remapping in **parse_scrutings.py** only caught 3 of the 15 votes that were impacted by the incorrect JO value of **RUANR5L15S2019IDS21507**.

Would you please let me know if you see more differences ? I may have incorrectly run the commands: still new to this :baby:

I was actually surprised to not see **more** differences because of the added remapping. But it turns out none of the additional remapping is associated with a vote, hence the lack of diff.

**Pull request closed without merging**
